[package]
name = "zhongwen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
qdrant-client = { version = "1.17.0", features = ["uuid"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
