services:
  qdrant:
    image: "qdrant/qdrant"
    ports:
      - "6333:6333" # REST API + Web Dashboard
      - "6334:6334" # gRPC
    volumes:
      - qdrant_stroage:/qdrant/storage

volumes:
  qdrant_stroage:
